### ISSUE TITLE
An inbuilt method to return input data for a GeoDataFrame would be nice

### ISSUE THREAD

**Issue by fwitte** [WZBSocialScienceCenter/geovoronoi#14]
Hi,
I feel that a method returning a dictionary containing the point x and y data along with the respective voronoi polygon would be a nice addition, to easily generate a GeoDataFrame. Or is there a method, that i oversaw? Without further inspection of the source code my quick and dirty postprocessing approach looks like this:

```python

# points_arr: numpy array of some points

gpd_input_dict= {
    'x': [],
    'y': [],
    'geometry': []
}

for pt, poly in region_pts.items():
    gpd_input_dict['x'] += [points_arr[poly[0]][0]]
    gpd_input_dict['y'] += [points_arr[poly[0]][1]]
    gpd_input_dict['geometry'] += [region_polys[pt]]


gdf_voronoi = gpd.GeoDataFrame(gpd_input_dict)
```
However, these information must be somewhere in the `voronoi_regions_from_coords` method as the mapping of the dictionaries is derived from it.

It might as well be numpy arrays or lists, just having something that returns data which can be directly sent to geopandas would be nice. Do you think it's worth adding some method like this?

Best regards and have a nice weekend

**Comment by internaut** [comment]
Thank you. There is a function to map each point ID to its Voronoi region, `points_to_region()` (the inverse of what is returned from `voronoi_regions_from_coords`), but nothing to generate input for a GeoDataFrame. I won't add this since this is not the primary purpose of this package and it also can be easily implemented on your own.

**Comment by fwitte** [comment]
Okay, thanks for letting me know!
