### ISSUE TITLE
Plotting a voronoi map over a street map with folium?

### ISSUE THREAD

**Issue by amca01** [WZBSocialScienceCenter/geovoronoi#18]
After far too much effort and being stupid, I finally have a Voronoi map.  Nice!  I do have a question though: is it possible to have this map drawn in folium, say, with a street map drawn on it?  Then I'd be able (I hope) to replace the data point labels with folium popups or tooltips.  And show the map in its geographic location.

I already have a nice folium map which shows the region and its data points.  So what I want to with it is put a Voronoi map over it (clearly then the colors would have to semi-transparent).  Is this possible?

Thanks!

**Comment by internaut** [comment]
I have no idea about folium, but since geovoronoi gives you [shapely polygons](https://shapely.readthedocs.io/en/stable/manual.html#polygons) you can do whatever you want with it, including exporting them to GeoJSON (see [interoperation](https://shapely.readthedocs.io/en/stable/manual.html#interoperation)) and hence using it with any other GIS software / package.

**Comment by amca01** [comment]
Thank you very much, internaut - I will check this out in more detail.  

In fact, it seems that the command "voronoi_regions_from_coords" gives a dictionary whose values are shapely polygons; so these can be added to a map directly, rather than using the "plot_voronoi_polys_with_points_in_area" function.  The dictionary keys relate to the places in the original geopandas file by the "region_pts" output.

All I have to do now is to work out how to add shapely files to a folium map ... which will require some fiddling.  Thank you again!

**Comment by slarrain** [comment]
Hey @amca01 did you ever manage to get it working? Any pointers, examples or tutorials?
