### ISSUE TITLE
How the distance is calculated?

### ISSUE THREAD

**Issue by QuantumDamage** [WZBSocialScienceCenter/geovoronoi#2]
Hi!
I found your module while working with geolocation data. My problem is, that final map is not as precise as I would expect. So I'm wandering if using your module could help me.

My workflow is following:
1. I have some geolocation data (lat,lon) and I'm putting it inside scipy voronoi. I'm calculating vertices.
2. I then calculate distance between vertices and points using geopy.distance.vincenty(coords_1, coords_2).km
3. I'm selecting biggest circle without points based on above calculations and I'm plotting them using folium.

Here's my result. 

![screenshot_2019-01-17 026](https://user-images.githubusercontent.com/4395139/51321921-519ff500-1a64-11e9-8ea8-728c7ced1d3e.png)

This circle should be biggest possible circle in Poland without marked points. I believe it should touch three points. There are to possible sources of this error:

1. I made a mistake somewhere.
2. One of modules calculates something not precisely enough. I know that scipy.spatial is designed to work with 2d-flat data, and folium and geopy should work nicely with non flat earth data.

So here is my question: **If I would replace default scipy voronoi with your geovoronoi, would it calculate voronoi cells correctly (on earth surface) based on latitude and longitude?** Did you used any geographical distance formula for voronoi cells?

If you are curious,
 my code is here: https://nbviewer.jupyter.org/gist/bbcf796d75dfe7a8d06040fcd73d35eb

**Comment by internaut** [comment]
First of all: GitHub issues are for **issues** you have with the software. Not for a Q&A with the developer. This is why I will close this.

The circle doesn't have to touch three points, because Voronoi regions are **polygons**.

Using geovoronoi wouldn't change anything, because I'm using SciPy internally, too, which probably uses Euclidian distance. You can convert the your coordinates to a suitable coordinate reference system (see https://epsg.io/ for one that fits for Poland). And then afterwards convert it back for plotting.
